[Site]
alias = {default_alias}
name = {default_name}
country_code = {default_country_code}
# puede ser: restarante, hotel o generic
type = hotel
ip = {default_ip}

[Config]
timezone = {default_timezone}
currency_code = {default_currency_code}

[Printers]
server = auto
#codigo fiscal
default_tipo_factura_codename  = B
default_tipo_factura_a_codename  = A
#nombre del comprobante
default_tipo_factura = B
ticket_template  = ticket
receipt_template = comandas
output = Database
receipt_id = 2
fiscal_id = 1

[Adicion]
reload_interval_timeout = 60000
cantidadCubiertosObligatorio = 0
preTicketHeader = COMPROBANTE DE CONSUMICION
usarCajero = 1
reload_interval = 19700
cobrada_hide_ms = 0
jqm_page_transition = 1
numeroMesaObligatorio = 0

[Horario]
corte_del_dia = 6


[Mesa]
imprimePrimeroRemito = 1
tituloMozo = Habitacion
tituloMesa = Reserva
tituloCubierto = Pasajero
tituloCliente = Cliente
usar_generica = 1
generica_name = Kiosko
generica_mozo_id = 1

[Mozo]
descuento_maximo = 15

[Restaurante]
tipofactura_name = C
valorCubierto = 0
#Id de la tabla iva_responsabilidades
# monotributista en este caso
iva_responsabilidad = 6
razon_social = RAZON SOCIAL S.A
ib = ND
mail = info@resto.com
cuit = 20303683268
domicilio = "Calle X Altura 2323 1º B"
domicilio_fiscal = "Calle FISCAL X Altura 1111"
punto_de_venta = 3
backup_mail = mails-backups@gmail.com
# Cantidad de decimales a mostrar en los totales y en el ticket
precision = 2

[Search]
Prg.presetForm = querystring

[Afip]
#Afip WS Code del tipo de factura ID, En este caso factura C
tipofactura_id = 11
# El concepto puede ser: 1 para productos, 2 para servicios, 3 para productos y servicios, 4 Otro
concepto = 2
inicio_actividades = 2010/12/12